resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/Dgarc359/david-garcia-world.git
      branch: test-cicd
      check_every: 20s

jobs:
  - name: dg-world-task
    plan:
      - get: repo
        trigger: true
      - task: build
        config: 
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          inputs:
            - name: repo
          run:
            path: which
            args: ["npm"]
      - task: deploy
