# This yaml file is leveraged by a remote concourse server
resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/Dgarc359/david-garcia-world.git
      branch: test-cicd
      check_every: 20s
  - name: node-image
    type: registry-image
    source:
      repository: node
      tag: 18

jobs:
  - name: dg-world-task
    plan:
      - get: node-image
      - get: repo
        trigger: true
      - task: install
        image: node-image
        config: 
          inputs:
            - name: repo
          outputs:
            - name: dependencies
              path: repo/node_modules
          platform: linux
          run:
            path: npm
            args: ["install"]
            dir: repo
      - task: build
        image: node-image
        config: 
          inputs:
            - name: repo
            - name: dependencies
              path: repo/node_modules
          platform: linux
          run:
            path: npm
            args: ["run", "build"]
            dir: repo
      - task: deploy 
        image: node-image
        config: 
          inputs:
            - name: repo
            - name: dependencies
              path: repo/node_modules
          platform: linux
          run:
            path: npm
            args: ["run", "deploy"]
            dir: repo
